[src]
iso = "gzlj01.iso"
src = "code"
link = ["code/target/powerpc-unknown-linux-gnu/release/librust.a"]
patch = "code/src/patch.asm"

[build]
map = "target/framework.map"
iso = "target/rom_hack.iso"

[link]
entries = ["init", "game_loop", "read_controller"]
base = "0x8040_1000"
